// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from "./app/__root"
import { Route as LoginImport } from "./app/login"
import { Route as AuthImport } from "./app/_auth"
import { Route as AuthIndexImport } from "./app/_auth/index"
import { Route as AuthPostsImport } from "./app/_auth/posts"
import { Route as AuthAboutImport } from "./app/_auth/about"
import { Route as AuthPostsPostIdImport } from "./app/_auth/posts/$postId"

// Create/Update Routes

const LoginRoute = LoginImport.update({
  path: "/login",
  getParentRoute: () => rootRoute,
} as any)

const AuthRoute = AuthImport.update({
  id: "/_auth",
  getParentRoute: () => rootRoute,
} as any)

const AuthIndexRoute = AuthIndexImport.update({
  path: "/",
  getParentRoute: () => AuthRoute,
} as any)

const AuthPostsRoute = AuthPostsImport.update({
  path: "/posts",
  getParentRoute: () => AuthRoute,
} as any)

const AuthAboutRoute = AuthAboutImport.update({
  path: "/about",
  getParentRoute: () => AuthRoute,
} as any)

const AuthPostsPostIdRoute = AuthPostsPostIdImport.update({
  path: "/$postId",
  getParentRoute: () => AuthPostsRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/_auth": {
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    "/login": {
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    "/_auth/about": {
      preLoaderRoute: typeof AuthAboutImport
      parentRoute: typeof AuthImport
    }
    "/_auth/posts": {
      preLoaderRoute: typeof AuthPostsImport
      parentRoute: typeof AuthImport
    }
    "/_auth/": {
      preLoaderRoute: typeof AuthIndexImport
      parentRoute: typeof AuthImport
    }
    "/_auth/posts/$postId": {
      preLoaderRoute: typeof AuthPostsPostIdImport
      parentRoute: typeof AuthPostsImport
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  AuthRoute.addChildren([
    AuthAboutRoute,
    AuthPostsRoute.addChildren([AuthPostsPostIdRoute]),
    AuthIndexRoute,
  ]),
  LoginRoute,
])
